DB_PATH = "user_accounts.db"
RESOURCE_CATALOG_URL = "http://localhost:8080"
SERVICE_ID = "account_manager"
SERVICE_NAME = "Account Manager"
SERVICE_DESCRIPTION = "Handles user authentication and authorization"
SERVICE_TYPE = "authentication"
API_PORT = 8088
REGISTRATION_INTERVAL = 60
LOGGING_ENABLED = True
LOG_LEVEL = "INFO"
LOG_FILE = "account_manager.log"