version: '3'

services:
  # MQTT Broker (Eclipse Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSockets port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  # Message Broker Service (Python wrapper)
  message-broker-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mqtt-broker
    environment:
      - BROKER_CONFIG_PATH=/app/config.json
      # Override the broker host to point to the Mosquitto container
      - MQTT_BROKER_HOST=mqtt-broker
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped